apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecost-grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecost-grafana
  template:
    metadata:
      labels:
        app: kubecost-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"  # Set Grafana admin password
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: "true"
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/"
        - name: kubecost
          image: kubecost/cost-analyzer:latest
          ports:
            - containerPort: 9090
          env:
            - name: COST_ANALYZER_UI_PORT
              value: "9090"  # Kubecost UI port
            - name: KUBECOST_NAMESPACE
              value: "kubecost"

