apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecost
  template:
    metadata:
      labels:
        app: kubecost
    spec:
      containers:
      - name: kubecost
        image: kubecost/cost-analyzer:latest
        resources:
          requests:
            cpu: "10m"
            memory: "55Mi"
          # limits:
            # cpu: "100m"
            # memory: "256Mi"
